### ISSUE TITLE
regarding controller after screen sharing

### ISSUE THREAD

**Issue by AnkithaSeepana** [adamyordan/laplace#2]
hii,

can you help in the context like,
after sharing the screen from laptop to mobile........from mobile can we have controller to operate the laptop screen???

**Comment by adamyordan** [comment]
Hi, in the demo, I connect the Xbox controller to my PC.
The mobile phone only mirrors the screen display.

**Comment by AnkithaSeepana** [comment]
Can you give some idea to integrate controller through mobile with your
screen mirroring.....

**Comment by adamyordan** [comment]
As far as I know, it's not possible to do that since my screen sharing project relies heavily on the client's Browser API. And there is no Browser API that supports input control (including controller DirectInput).

Another alternative approach that is possible is: by creating a standalone app, and have the client install and execute the app. Installed apps will have system permission to control inputs.

**Comment by AnkithaSeepana** [comment]
Okay.... Thank you
